name: Compile and Deploy to GitHub Page
on:
  push:
    branches:
      - blogPages
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        ref: refs/heads/source

    - uses: actions/setup-node@v1
      with:
        node_version: '8.x'

    - name: Setup Git user info and env
      env:
        M_GITHUB_PAGES_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
      run: |
        git config --global user.email "xycg.sky@gmail.com"
        git config --global user.name "Zmingfeng"
        sed -i "s/DEPLOY_TOKEN/$DEPLOY_TOKEN/g" ./_config.yml
    - name: Install dependencies
      run: npm ci
    - name: Compile and deploy blog
      run: hexo clean && hexo g && hexo d
